# Generated by Django 4.2.7 on 2025-03-24 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wizards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wizard",
            name="power",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
